<?php

namespace Database\Seeders;

use App\Enums\Crm\ActivityType;
use App\Enums\Crm\CommissionStatus;
use App\Enums\Crm\CommissionType;
use App\Enums\Crm\Grade;
use App\Enums\Crm\InstallationStatus;
use App\Enums\Crm\LeadSource;
use App\Enums\Crm\LeadStatus;
use App\Enums\Crm\PaymentMethod;
use App\Enums\Crm\WithdrawalStatus;
use App\Enums\UserRole;
use App\Models\Crm\Commission;
use App\Models\Crm\CommercialProfile;
use App\Models\Crm\Installation;
use App\Models\Crm\Lead;
use App\Models\Crm\LeadActivity;
use App\Models\Crm\Team;
use App\Models\Crm\TechnicianProfile;
use App\Models\Crm\UserGrade;
use App\Models\Crm\Wallet;
use App\Models\Crm\Withdrawal;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class CrmSeeder extends Seeder
{
    private array $commercials = [];
    private array $technicians = [];
    private array $teams = [];
    private array $leads = [];

    public function run(): void
    {
        $this->command->info('Seeding CRM system...');

        $this->createTeams();
        $this->createCommercials();
        $this->createTechnicians();
        $this->createTeamLeaders();
        $this->createLeads();
        $this->createInstallations();
        $this->createCommissions();
        $this->createWithdrawals();

        $this->command->info('CRM system seeded successfully!');
    }

    private function createTeams(): void
    {
        $this->command->info('Creating teams...');

        $teamsData = [
            [
                'name' => 'Team Abidjan Nord',
                'zone' => 'Cocody/Plateau',
                'monthly_target' => 20,
                'is_active' => true,
            ],
            [
                'name' => 'Team Abidjan Sud',
                'zone' => 'Marcory/Treichville',
                'monthly_target' => 15,
                'is_active' => true,
            ],
            [
                'name' => 'Team Bouaké',
                'zone' => 'Bouaké',
                'monthly_target' => 10,
                'is_active' => true,
            ],
        ];

        foreach ($teamsData as $data) {
            $this->teams[] = Team::create($data);
        }
    }

    private function createCommercials(): void
    {
        $this->command->info('Creating commercials...');

        $commercialsData = [
            ['name' => 'Kouamé Achi', 'email' => 'kouame@menupro.ci', 'city' => 'Cocody', 'team_index' => 0, 'conversions' => 8],
            ['name' => 'Diabaté Fanta', 'email' => 'diabate@menupro.ci', 'city' => 'Plateau', 'team_index' => 0, 'conversions' => 12],
            ['name' => 'Traoré Ibrahim', 'email' => 'traore@menupro.ci', 'city' => 'Marcory', 'team_index' => 1, 'conversions' => 4],
            ['name' => 'Koné Aminata', 'email' => 'kone@menupro.ci', 'city' => 'Treichville', 'team_index' => 1, 'conversions' => 22],
            ['name' => 'Bamba Moussa', 'email' => 'bamba@menupro.ci', 'city' => 'Bouaké', 'team_index' => 2, 'conversions' => 15],
            ['name' => 'Yao Adjoua', 'email' => 'yao@menupro.ci', 'city' => 'Cocody', 'team_index' => 0, 'conversions' => 3],
            ['name' => 'Coulibaly Drissa', 'email' => 'coulibaly@menupro.ci', 'city' => 'Marcory', 'team_index' => 1, 'conversions' => 19],
            ['name' => 'N\'Guessan Affoué', 'email' => 'nguessan@menupro.ci', 'city' => 'Bouaké', 'team_index' => 2, 'conversions' => 7],
        ];

        foreach ($commercialsData as $index => $data) {
            $user = User::create([
                'name' => $data['name'],
                'email' => $data['email'],
                'password' => Hash::make('password'),
                'role' => UserRole::COMMERCIAL,
                'city' => $data['city'],
                'is_active' => true,
                'email_verified_at' => now(),
            ]);

            $profile = CommercialProfile::create([
                'user_id' => $user->id,
                'city' => $data['city'],
                'statut_metier' => 'actif',
                'verification_status' => 'verified',
                'approved_at' => now()->subDays(rand(30, 90)),
                'team_id' => $this->teams[$data['team_index']]->id,
            ]);

            // Badge ID is auto-generated by the model
            // but let's set a custom one for better readability
            $profile->update(['badge_id' => 'MP-' . str_pad($index + 1, 3, '0', STR_PAD_LEFT)]);

            // Create UserGrade based on conversions
            $grade = Grade::fromConversions($data['conversions']);
            UserGrade::create([
                'user_id' => $user->id,
                'current_grade' => $grade,
                'total_conversions' => $data['conversions'],
                'grade_updated_at' => now()->subDays(rand(10, 60)),
            ]);

            // Create Wallet with some balance
            $balance = rand(50000, 500000); // 50k to 500k FCFA
            Wallet::create([
                'user_id' => $user->id,
                'balance_cents' => $balance,
                'total_earned_cents' => rand($balance, $balance * 2),
                'total_withdrawn_cents' => rand(0, $balance / 2),
            ]);

            // Add to team members
            $this->teams[$data['team_index']]->members()->attach($user->id, [
                'role_in_team' => 'commercial',
                'joined_at' => now()->subDays(rand(30, 90)),
            ]);

            $this->commercials[] = $user;
        }
    }

    private function createTechnicians(): void
    {
        $this->command->info('Creating technicians...');

        $techniciansData = [
            ['name' => 'Koffi Jean-Marc', 'email' => 'koffi@menupro.ci', 'speciality' => 'POS & Matériel', 'zone' => 'Abidjan', 'team_index' => 0],
            ['name' => 'Ouattara Seydou', 'email' => 'ouattara@menupro.ci', 'speciality' => 'Réseau & Wifi', 'zone' => 'Abidjan', 'team_index' => 1],
            ['name' => 'Dao Mathias', 'email' => 'dao@menupro.ci', 'speciality' => 'Installation complète', 'zone' => 'Bouaké', 'team_index' => 2],
        ];

        foreach ($techniciansData as $data) {
            $user = User::create([
                'name' => $data['name'],
                'email' => $data['email'],
                'password' => Hash::make('password'),
                'role' => UserRole::TECHNICIAN,
                'city' => $data['zone'],
                'is_active' => true,
                'email_verified_at' => now(),
            ]);

            TechnicianProfile::create([
                'user_id' => $user->id,
                'speciality' => $data['speciality'],
                'zone_geographique' => $data['zone'],
                'disponible' => true,
                'team_id' => $this->teams[$data['team_index']]->id,
                'certifications' => ['POS Installation', 'Network Setup'],
            ]);

            // Create Wallet
            Wallet::create([
                'user_id' => $user->id,
                'balance_cents' => rand(20000, 150000),
                'total_earned_cents' => rand(100000, 300000),
                'total_withdrawn_cents' => rand(50000, 150000),
            ]);

            // Add to team members
            $this->teams[$data['team_index']]->members()->attach($user->id, [
                'role_in_team' => 'technician',
                'joined_at' => now()->subDays(rand(60, 180)),
            ]);

            $this->technicians[] = $user;
        }
    }

    private function createTeamLeaders(): void
    {
        $this->command->info('Creating team leaders...');

        $leadersData = [
            ['name' => 'Assomption Kouassi', 'email' => 'kouassi@menupro.ci', 'city' => 'Cocody', 'team_index' => 0],
            ['name' => 'Laurent Gbagbo Jr', 'email' => 'gbagbo@menupro.ci', 'city' => 'Marcory', 'team_index' => 1],
            ['name' => 'Marie-Claire Soro', 'email' => 'soro@menupro.ci', 'city' => 'Bouaké', 'team_index' => 2],
        ];

        foreach ($leadersData as $data) {
            $user = User::create([
                'name' => $data['name'],
                'email' => $data['email'],
                'password' => Hash::make('password'),
                'role' => UserRole::TEAM_LEADER,
                'city' => $data['city'],
                'is_active' => true,
                'email_verified_at' => now(),
            ]);

            // Create Wallet
            Wallet::create([
                'user_id' => $user->id,
                'balance_cents' => rand(100000, 800000),
                'total_earned_cents' => rand(500000, 1500000),
                'total_withdrawn_cents' => rand(200000, 700000),
            ]);

            // Set as team leader
            $this->teams[$data['team_index']]->update(['leader_id' => $user->id]);
        }
    }

    private function createLeads(): void
    {
        $this->command->info('Creating leads...');

        $restaurants = [
            // NOUVEAU (8)
            ['name' => 'Maquis du Bonheur', 'manager' => 'Kouadio Ange', 'city' => 'Cocody', 'status' => LeadStatus::NOUVEAU, 'source' => LeadSource::TERRAIN],
            ['name' => 'Restaurant Le Délice', 'manager' => 'Fadika Sophie', 'city' => 'Plateau', 'status' => LeadStatus::NOUVEAU, 'source' => LeadSource::WEB],
            ['name' => 'Garba Express', 'manager' => 'Traoré Sékou', 'city' => 'Marcory', 'status' => LeadStatus::NOUVEAU, 'source' => LeadSource::TERRAIN],
            ['name' => 'Chez Tantie Aya', 'manager' => 'N\'Dri Aya', 'city' => 'Treichville', 'status' => LeadStatus::NOUVEAU, 'source' => LeadSource::WHATSAPP],
            ['name' => 'Le Jardin Gourmand', 'manager' => 'Bamba Rachid', 'city' => 'Bouaké', 'status' => LeadStatus::NOUVEAU, 'source' => LeadSource::REFERRAL],
            ['name' => 'Pizza Corner CI', 'manager' => 'Koné Lamine', 'city' => 'Cocody', 'status' => LeadStatus::NOUVEAU, 'source' => LeadSource::INBOUND],
            ['name' => 'Brochettes du Plateau', 'manager' => 'Yao Christian', 'city' => 'Plateau', 'status' => LeadStatus::NOUVEAU, 'source' => LeadSource::TERRAIN],
            ['name' => 'Maquis VIP', 'manager' => 'Ouattara Mariam', 'city' => 'Cocody', 'status' => LeadStatus::NOUVEAU, 'source' => LeadSource::WEB],

            // CONTACTE (6)
            ['name' => 'Le Rocher', 'manager' => 'Sanogo Ibrahim', 'city' => 'Marcory', 'status' => LeadStatus::CONTACTE, 'source' => LeadSource::TERRAIN],
            ['name' => 'Attiéké Poisson Palace', 'manager' => 'Diabaté Adjoua', 'city' => 'Treichville', 'status' => LeadStatus::CONTACTE, 'source' => LeadSource::WHATSAPP],
            ['name' => 'Resto Moderne', 'manager' => 'Koffi Marc', 'city' => 'Bouaké', 'status' => LeadStatus::CONTACTE, 'source' => LeadSource::INBOUND],
            ['name' => 'Le Bambou Doré', 'manager' => 'Soro Fatim', 'city' => 'Cocody', 'status' => LeadStatus::CONTACTE, 'source' => LeadSource::REFERRAL],
            ['name' => 'Tchep & Sauce', 'manager' => 'Coulibaly Aicha', 'city' => 'Plateau', 'status' => LeadStatus::CONTACTE, 'source' => LeadSource::TERRAIN],
            ['name' => 'Le Continental', 'manager' => 'Touré Hassan', 'city' => 'Marcory', 'status' => LeadStatus::CONTACTE, 'source' => LeadSource::WEB],

            // DEMONSTRATION (5)
            ['name' => 'Chez Bintu', 'manager' => 'Diallo Bintu', 'city' => 'Treichville', 'status' => LeadStatus::DEMONSTRATION, 'source' => LeadSource::TERRAIN],
            ['name' => 'Poulet DG Express', 'manager' => 'Gbagbo Junior', 'city' => 'Bouaké', 'status' => LeadStatus::DEMONSTRATION, 'source' => LeadSource::WHATSAPP],
            ['name' => 'Le Parisien', 'manager' => 'Konan Sylvie', 'city' => 'Cocody', 'status' => LeadStatus::DEMONSTRATION, 'source' => LeadSource::REFERRAL],
            ['name' => 'Maquis 2 Plateaux', 'manager' => 'N\'Guessan Paul', 'city' => 'Cocody', 'status' => LeadStatus::DEMONSTRATION, 'source' => LeadSource::INBOUND],
            ['name' => 'Resto du Port', 'manager' => 'Bony Christelle', 'city' => 'Treichville', 'status' => LeadStatus::DEMONSTRATION, 'source' => LeadSource::TERRAIN],

            // RELANCE (4)
            ['name' => 'Le Wôrô Wôrô', 'manager' => 'Bakayoko Moussa', 'city' => 'Marcory', 'status' => LeadStatus::RELANCE, 'source' => LeadSource::WEB],
            ['name' => 'Chez Marie', 'manager' => 'Kouassi Marie', 'city' => 'Plateau', 'status' => LeadStatus::RELANCE, 'source' => LeadSource::TERRAIN],
            ['name' => 'Garbadrome VIP', 'manager' => 'Dao Martin', 'city' => 'Bouaké', 'status' => LeadStatus::RELANCE, 'source' => LeadSource::WHATSAPP],
            ['name' => 'Le Rendez-vous', 'manager' => 'Assouan Eric', 'city' => 'Cocody', 'status' => LeadStatus::RELANCE, 'source' => LeadSource::REFERRAL],

            // SIGNATURE (3)
            ['name' => 'Chez Victorine', 'manager' => 'Kouadio Victorine', 'city' => 'Marcory', 'status' => LeadStatus::SIGNATURE, 'source' => LeadSource::TERRAIN],
            ['name' => 'La Terrasse', 'manager' => 'Koné Abdoul', 'city' => 'Plateau', 'status' => LeadStatus::SIGNATURE, 'source' => LeadSource::INBOUND],
            ['name' => 'Espace Fraîcheur', 'manager' => 'Traoré Aissata', 'city' => 'Treichville', 'status' => LeadStatus::SIGNATURE, 'source' => LeadSource::REFERRAL],

            // INSTALLATION (2)
            ['name' => 'Le Coin des Saveurs', 'manager' => 'Bamba Salif', 'city' => 'Bouaké', 'status' => LeadStatus::INSTALLATION, 'source' => LeadSource::TERRAIN],
            ['name' => 'Chez Adjoua', 'manager' => 'Yao Adjoua', 'city' => 'Cocody', 'status' => LeadStatus::INSTALLATION, 'source' => LeadSource::WHATSAPP],

            // ACTIF (2)
            ['name' => 'Restaurant Le Palmier', 'manager' => 'Ouattara Ismaël', 'city' => 'Marcory', 'status' => LeadStatus::ACTIF, 'source' => LeadSource::TERRAIN],
            ['name' => 'Maquis Chez Tantine', 'manager' => 'Konan Béatrice', 'city' => 'Plateau', 'status' => LeadStatus::ACTIF, 'source' => LeadSource::REFERRAL],
        ];

        foreach ($restaurants as $restaurant) {
            // Assign to commercial based on city
            $commercial = $this->getCommercialForCity($restaurant['city']);
            $team = $this->getTeamForCity($restaurant['city']);

            $lead = Lead::create([
                'restaurant_name' => $restaurant['name'],
                'manager_name' => $restaurant['manager'],
                'phone' => $this->generateIvoirianPhone(),
                'email' => strtolower(str_replace(' ', '', $restaurant['name'])) . '@email.ci',
                'address' => $this->getRandomAddress($restaurant['city']),
                'city' => $restaurant['city'],
                'latitude' => $this->getLatitude($restaurant['city']),
                'longitude' => $this->getLongitude($restaurant['city']),
                'status' => $restaurant['status'],
                'source' => $restaurant['source'],
                'assigned_to' => $commercial->id,
                'team_id' => $team->id,
                'score' => rand(50, 100),
                'next_action_at' => $restaurant['status']->isActive() ? now()->addDays(rand(1, 7)) : null,
                'converted_at' => $restaurant['status'] === LeadStatus::ACTIF ? now()->subDays(rand(5, 30)) : null,
            ]);

            $this->leads[] = $lead;

            // Add 2-3 activities per lead
            $this->createActivitiesForLead($lead, $commercial);
        }
    }

    private function createActivitiesForLead(Lead $lead, User $commercial): void
    {
        $activityCount = rand(2, 3);
        $activities = [
            ['type' => ActivityType::CALL, 'desc' => 'Premier contact téléphonique - Introduction MenuPro'],
            ['type' => ActivityType::VISIT, 'desc' => 'Visite terrain effectuée - Prise de contact avec le gérant'],
            ['type' => ActivityType::DEMO, 'desc' => 'Démonstration du système POS et des fonctionnalités'],
            ['type' => ActivityType::WHATSAPP, 'desc' => 'Envoi de la documentation via WhatsApp'],
            ['type' => ActivityType::NOTE, 'desc' => 'Lead très intéressé, demande un devis personnalisé'],
            ['type' => ActivityType::CALL, 'desc' => 'Suivi - Discussion sur les modalités de paiement'],
        ];

        for ($i = 0; $i < $activityCount; $i++) {
            $activity = $activities[array_rand($activities)];
            LeadActivity::create([
                'lead_id' => $lead->id,
                'user_id' => $commercial->id,
                'type' => $activity['type'],
                'description' => $activity['desc'],
                'metadata' => [
                    'duration' => rand(10, 45),
                    'outcome' => ['positive', 'neutral', 'need_followup'][rand(0, 2)],
                ],
                'created_at' => now()->subDays(rand(1, 30)),
            ]);
        }
    }

    private function createInstallations(): void
    {
        $this->command->info('Creating installations...');

        // Get leads that are in INSTALLATION or ACTIF status
        $installableLeads = collect($this->leads)
            ->filter(fn($lead) => in_array($lead->status, [LeadStatus::INSTALLATION, LeadStatus::ACTIF]))
            ->values();

        // TERMINEE (2)
        for ($i = 0; $i < 2; $i++) {
            if ($i >= $installableLeads->count()) break;
            $lead = $installableLeads[$i];

            Installation::create([
                'lead_id' => $lead->id,
                'technician_id' => $this->technicians[array_rand($this->technicians)]->id,
                'scheduled_at' => now()->subDays(rand(5, 15)),
                'started_at' => now()->subDays(rand(4, 14)),
                'completed_at' => now()->subDays(rand(3, 13)),
                'status' => InstallationStatus::TERMINEE,
                'notes' => 'Installation réussie. Client satisfait.',
                'equipment' => ['POS Terminal', 'Receipt Printer', 'Router'],
                'photos' => [],
                'rating' => rand(4, 5),
            ]);
        }

        // PLANIFIEE (2)
        for ($i = 2; $i < 4; $i++) {
            if ($i >= $installableLeads->count()) break;
            $lead = $installableLeads[$i];

            Installation::create([
                'lead_id' => $lead->id,
                'technician_id' => $this->technicians[array_rand($this->technicians)]->id,
                'scheduled_at' => now()->addDays(rand(1, 7)),
                'status' => InstallationStatus::PLANIFIEE,
                'notes' => 'Installation planifiée avec le gérant.',
                'equipment' => ['POS Terminal', 'Receipt Printer'],
                'photos' => [],
            ]);
        }

        // EN_COURS (1)
        if ($installableLeads->count() >= 5) {
            $lead = $installableLeads[4];
            Installation::create([
                'lead_id' => $lead->id,
                'technician_id' => $this->technicians[array_rand($this->technicians)]->id,
                'scheduled_at' => now()->subHours(3),
                'started_at' => now()->subHours(2),
                'status' => InstallationStatus::EN_COURS,
                'notes' => 'Installation en cours. Configuration du réseau.',
                'equipment' => ['POS Terminal', 'Receipt Printer', 'Router', 'Kitchen Display'],
                'photos' => [],
            ]);
        }
    }

    private function createCommissions(): void
    {
        $this->command->info('Creating commissions...');

        // Get leads that reached SIGNATURE or beyond
        $convertedLeads = collect($this->leads)
            ->filter(fn($lead) => in_array($lead->status, [
                LeadStatus::SIGNATURE,
                LeadStatus::INSTALLATION,
                LeadStatus::ACTIF
            ]));

        foreach ($convertedLeads as $lead) {
            $commercial = User::find($lead->assigned_to);
            $wallet = $commercial->crmWallet;

            // Commission SIGNATURE
            Commission::create([
                'wallet_id' => $wallet->id,
                'user_id' => $commercial->id,
                'type' => CommissionType::SIGNATURE,
                'status' => CommissionStatus::VALIDATED,
                'amount_cents' => 50000, // 50,000 FCFA
                'source_type' => Lead::class,
                'source_id' => $lead->id,
                'description' => "Commission signature - {$lead->restaurant_name}",
                'metadata' => ['lead_id' => $lead->id],
                'validated_at' => now()->subDays(rand(1, 10)),
            ]);

            // Commission INSTALLATION (if lead has installation)
            if (in_array($lead->status, [LeadStatus::INSTALLATION, LeadStatus::ACTIF])) {
                Commission::create([
                    'wallet_id' => $wallet->id,
                    'user_id' => $commercial->id,
                    'type' => CommissionType::INSTALLATION,
                    'status' => $lead->status === LeadStatus::ACTIF ? CommissionStatus::PAID : CommissionStatus::VALIDATED,
                    'amount_cents' => 75000, // 75,000 FCFA
                    'source_type' => Lead::class,
                    'source_id' => $lead->id,
                    'description' => "Commission installation - {$lead->restaurant_name}",
                    'metadata' => ['lead_id' => $lead->id],
                    'validated_at' => now()->subDays(rand(1, 5)),
                ]);
            }
        }

        // Add some bonus commissions for top performers
        $topCommercials = collect($this->commercials)->random(2);
        foreach ($topCommercials as $commercial) {
            $wallet = $commercial->crmWallet;
            Commission::create([
                'wallet_id' => $wallet->id,
                'user_id' => $commercial->id,
                'type' => CommissionType::BONUS_PERFORMANCE,
                'status' => CommissionStatus::PAID,
                'amount_cents' => 100000, // 100,000 FCFA
                'source_type' => null,
                'source_id' => null,
                'description' => 'Bonus performance mensuel',
                'metadata' => ['period' => now()->format('Y-m')],
                'validated_at' => now()->subDays(rand(5, 15)),
            ]);
        }
    }

    private function createWithdrawals(): void
    {
        $this->command->info('Creating withdrawals...');

        // Create 3 pending withdrawals
        $commercials = collect($this->commercials)->random(3);

        foreach ($commercials as $commercial) {
            $wallet = $commercial->crmWallet;
            $amount = rand(50000, min(200000, $wallet->balance_cents));

            Withdrawal::create([
                'wallet_id' => $wallet->id,
                'user_id' => $commercial->id,
                'amount_cents' => $amount,
                'status' => WithdrawalStatus::PENDING,
                'payment_method' => [
                    PaymentMethod::WAVE,
                    PaymentMethod::ORANGE_MONEY,
                    PaymentMethod::MTN,
                ][rand(0, 2)],
            ]);

            // Deduct from wallet (balance is debited when withdrawal is requested)
            $wallet->decrement('balance_cents', $amount);
        }
    }

    // Helper methods

    private function getCommercialForCity(string $city): User
    {
        // Map cities to commercials based on their zones
        $cityToCommercial = [
            'Cocody' => [0, 1, 5], // Team Abidjan Nord
            'Plateau' => [0, 1, 5],
            'Marcory' => [2, 6], // Team Abidjan Sud
            'Treichville' => [3, 2],
            'Bouaké' => [4, 7], // Team Bouaké
        ];

        $possibleCommercials = $cityToCommercial[$city] ?? [0];
        $index = $possibleCommercials[array_rand($possibleCommercials)];

        return $this->commercials[$index];
    }

    private function getTeamForCity(string $city): Team
    {
        $cityToTeam = [
            'Cocody' => 0,
            'Plateau' => 0,
            'Marcory' => 1,
            'Treichville' => 1,
            'Bouaké' => 2,
        ];

        $index = $cityToTeam[$city] ?? 0;
        return $this->teams[$index];
    }

    private function generateIvoirianPhone(): string
    {
        $prefixes = ['07', '05', '01'];
        $prefix = $prefixes[array_rand($prefixes)];
        $number = str_pad(rand(10000000, 99999999), 8, '0', STR_PAD_LEFT);

        return $prefix . $number;
    }

    private function getRandomAddress(string $city): string
    {
        $addresses = [
            'Cocody' => ['Rue des Jardins, Cocody', 'Boulevard Latrille, Cocody', 'Avenue de la Paix, 2 Plateaux'],
            'Plateau' => ['Avenue Chardy, Plateau', 'Rue du Commerce, Plateau', 'Boulevard Angoulvant'],
            'Marcory' => ['Zone 4, Marcory', 'Boulevard VGE, Marcory', 'Rue de la Mairie, Marcory'],
            'Treichville' => ['Avenue 7, Treichville', 'Boulevard de Marseille', 'Rue 12, Treichville'],
            'Bouaké' => ['Quartier Commerce, Bouaké', 'Avenue Houphouët-Boigny', 'Quartier Belleville'],
        ];

        $cityAddresses = $addresses[$city] ?? ['Adresse non spécifiée'];
        return $cityAddresses[array_rand($cityAddresses)];
    }

    private function getLatitude(string $city): float
    {
        $coordinates = [
            'Cocody' => 5.3599,
            'Plateau' => 5.3277,
            'Marcory' => 5.2967,
            'Treichville' => 5.3036,
            'Bouaké' => 7.6908,
        ];

        $base = $coordinates[$city] ?? 5.3599;
        return round($base + (rand(-50, 50) / 10000), 7);
    }

    private function getLongitude(string $city): float
    {
        $coordinates = [
            'Cocody' => -3.9873,
            'Plateau' => -4.0266,
            'Marcory' => -3.9894,
            'Treichville' => -4.0175,
            'Bouaké' => -5.0342,
        ];

        $base = $coordinates[$city] ?? -3.9873;
        return round($base + (rand(-50, 50) / 10000), 7);
    }
}
